<div id="gal1">
<div class="gallerimain">
<h2>Galleri 1</h2>
<p>Klikk p&aring; de sm&aring; bildene for &aring; se forst&oslash;rrelse.</p>
<br />
<div id="webtable">
<ul id="portfolio">
<li class="new-flight"><a title="Cappelen forlag: New Flight" rel="imagebox-new" href="assets/images/books/New_Flight/newflight_doggie_big.jpg"><img src="assets/images/books/New_Flight/Thumnails/newflight_doggie_small.jpg" alt="nf_doggie" width="77" height="105" /></a></li>
<li class="new-flight"><a title="Cappelen forlag: New Flight" rel="imagebox-new" href="assets/images/books/New_Flight/newflight_jinnie_big.jpg"><img src="assets/images/books/New_Flight/Thumnails/newflight_jinnie_small.jpg" alt="nf_jinnie" width="77" height="105" /></a></li>
<li class="det-hemmelige-eventyret"><a title="Manus forlag: Det hemmelige eventyret" rel="imagebox-even" href="assets/images/books/Hemmelig/trehus.jpg"><img src="assets/images/books/Hemmelig/Thumbs/trehus_small.jpg" alt="hemmelig_alvelin" width="77" height="105" /></a></li>
<li class="amina"><a title="Forlaget fag og kultur: M&oslash;t Amina" rel="imagebox-amina" href="assets/images/books/Amina/amina_halloween_big.jpg"><img src="assets/images/books/Amina/Thumbnails/amina_halloween_small.jpg" alt="amina_halloween" width="77" height="105" /></a></li>
<li class="cumulus"><a title="Aschehoug forlag: Cumulus" rel="imagebox-cumulus" href="assets/images/books/Cumulus/cumulus_baker_big.jpg"><img src="assets/images/books/Cumulus/Thumbnails/cumulus_baker_small.jpg" alt="cumulus_baker" width="77" height="105" /></a></li>
<li class="messages-from-the-wee-folk"><a title="Windpferd Verlag, AGMuller: Messages from the Wee Folk" rel="imagebox-wee" href="assets/images/books/Wee_Folk/weefolk_air_big.jpg"><img src="assets/images/books/Wee_Folk/Thumbs/weefolk_air_small.jpg" alt="wf_pegasus" width="73" height="105" /></a></li>
<li class="wisdom-of-four-winds"><a title="StonePrint Press, Kamsha Verlag: Wisdom of the Four Winds" rel="imagebox-four" href="assets/images/books/Wisdom/wisdom_dragonfly_big.jpg"><img src="assets/images/books/Wisdom/Thumbs/wisdom_dragonfly_small.jpg" alt="wfw_dragonfly" width="62" height="106" /></a></li>
<li class="new-flight"><a title="Cappelen forlag: New Flight" rel="imagebox-new" href="assets/images/books/New_Flight/newflight_brokenlimbs_big.jpg"><img src="assets/images/books/New_Flight/Thumnails/newflight_brokenlimbs_small.jpg" alt="nf_sykehus" width="77" height="105" /></a></li>
<li class="new-flight"><a title="Cappelen forlag: New Flight" rel="imagebox-new" href="assets/images/books/New_Flight/newflight_camel_big.jpg"><img src="assets/images/books/New_Flight/Thumnails/newflight_camel_small.jpg" alt="nf_kamel" width="77" height="105" /></a></li>
<li class="det-hemmelige-eventyret"><a title="Manus forlag: Det hemmelige eventyret" rel="imagebox-even" href="assets/images/books/Hemmelig/tunnel.jpg"><img src="assets/images/books/Hemmelig/Thumbs/tunnel_small.jpg" alt="hemmelig_tunnel" width="77" height="105" /></a></li>
<li class="amina"><a title="Forlaget fag og kultur: M&oslash;t Amina" rel="imagebox-amina" href="assets/images/books/Amina/amina_dentist_big.jpg"><img src="assets/images/books/Amina/Thumbnails/amina_dentist_small.jpg" alt="amina dentist" width="77" height="105" /></a></li>
<li class="cumulus"><a title="Aschehoug forlag: Cumulus" rel="imagebox-cumulus" href="assets/images/books/Cumulus/cumulus_drager_big.jpg"><img src="assets/images/books/Cumulus/Thumbnails/cumulus_drager_small.jpg" alt="cumulus_drager" width="77" height="105" /></a></li>
<li class="messages-from-the-wee-folk"><a title="Windpferd Verlag, AGMuller: Messages from the Wee Folk" rel="imagebox-wee" href="assets/images/books/Wee_Folk/weefolk_celebrate_big.jpg"><img src="assets/images/books/Wee_Folk/Thumbs/weefolk_celebrate_small.jpg" alt="wf_celebrate" width="73" height="105" /></a></li>
<li class="wisdom-of-four-winds"><a title="StonePrint Press, Kamsha Verlag: Wisdom of the Four Winds" rel="imagebox-four" href="assets/images/books/Wisdom/wisdom_tuatara_big.jpg"><img src="assets/images/books/Wisdom/Thumbs/wisdom_tuatara_small.jpg" alt="wfw_tuatara" width="62" height="107" /></a></li>
<li class="new-flight"><a title="Cappelen forlag: New Flight" rel="imagebox-new" href="assets/images/books/New_Flight/newflight_hippo_big.jpg"><img src="assets/images/books/New_Flight/Thumnails/newflight_hippo_small.jpg" alt="nf_hippo" width="77" height="105" /></a></li>
<li class="new-flight"><a title="Cappelen forlag: New Flight" rel="imagebox-new" href="assets/images/books/New_Flight/newflight_indianemor_big.jpg"><img src="assets/images/books/New_Flight/Thumnails/newflight_indianermor_small.jpg" alt="nf_indianermor" width="77" height="105" /></a></li>
<li class="det-hemmelige-eventyret"><a title="Manus forlag: Det hemmelige eventyret" rel="imagebox-even" href="assets/images/books/Hemmelig/kongen.jpg"><img src="assets/images/books/Hemmelig/Thumbs/kongenl_small.jpg" alt="hemmelig_konge" width="77" height="105" /></a></li>
<li class="amina"><a title="Forlaget fag og kultur: M&oslash;t Amina" rel="imagebox-amina" href="assets/images/books/Amina/amina_lucia_big.jpg"><img src="assets/images/books/Amina/Thumbnails/amina_lucia_small.jpg" alt="amina_lucia" width="77" height="105" /></a></li>
<li class="cumulus"><a title="Aschehoug forlag: Cumulus" rel="imagebox-cumulus" href="assets/images/books/Cumulus/cumulus_filosofer_big.jpg"><img src="assets/images/books/Cumulus/Thumbnails/cumulus_filosofer_small.jpg" alt="cumulus_filisofer" width="77" height="105" /></a></li>
<li class="messages-from-the-wee-folk"><a title="Windpferd Verlag, AGMuller: Messages from the Wee Folk" rel="imagebox-wee" href="assets/images/books/Wee_Folk/weefolk_courage_big.jpg"><img src="assets/images/books/Wee_Folk/Thumbs/weefolk_courage_small.jpg" alt="wf_courage" width="74" height="105" /></a></li>
<li class="wisdom-of-four-winds"><a title="StonePrint Press, Kamsha Verlag: Wisdom of the Four Winds" rel="imagebox-four" href="assets/images/books/Wisdom/wisdom_fantail_big.jpg"><img src="assets/images/books/Wisdom/Thumbs/wisdom_fantail_small.jpg" alt="wfw_fantail" width="62" height="105" /></a></li>
<li class="new-flight"><a title="Cappelen forlag: New Flight" rel="imagebox-new" href="assets/images/books/New_Flight/newflight_grandmarap_big.jpg"><img src="assets/images/books/New_Flight/Thumnails/newflight_grandmarap_small.jpg" alt="nf_grandmarap" width="77" height="105" /></a></li>
<li class="new-flight"><a title="Cappelen forlag: New Flight" rel="imagebox-new" href="assets/images/books/New_Flight/newflight_indianer_big.jpg"><img src="assets/images/books/New_Flight/Thumnails/newflight_indianer_small.jpg" alt="nf_indianer" width="77" height="105" /></a></li>
<li class="new-flight"><a title="Cappelen forlag: New Flight" rel="imagebox-new" href="assets/images/books/New_Flight/newflight_mangedyr_big.jpg"><img src="assets/images/books/New_Flight/Thumnails/newflight_mangedyr_small.jpg" alt="nf_mangedyr" width="77" height="105" /></a></li>
<li class="amina"><a title="Forlaget fag og kultur: M&oslash;t Amina" rel="imagebox-amina" href="assets/images/books/Amina/amina_schoolyard_big.jpg"><img src="assets/images/books/Amina/Thumbnails/amina_schoolyard_small.jpg" alt="amina_skolegard" width="77" height="105" /></a></li>
<li class="cumulus"><a title="Aschehoug forlag: Cumulus" rel="imagebox-cumulus" href="assets/images/books/Cumulus/cumulus_gravemaskin_big.jpg"><img src="assets/images/books/Cumulus/Thumbnails/cumulus_gravemaskin_small.jpg" alt="cumulus_gravemaskin" width="77" height="105" /></a></li>
<li class="messages-from-the-wee-folk"><a title="Windpferd Verlag, AGMuller: Messages from the Wee Folk" rel="imagebox-wee" href="assets/images/books/Wee_Folk/weefolk_journey_big.jpg"><img src="assets/images/books/Wee_Folk/Thumbs/weefolk_journey_small.jpg" alt="wf_journey" width="73" height="105" /></a></li>
<li class="wisdom-of-four-winds"><a title="StonePrint Press, Kamsha Verlag: Wisdom of the Four Winds" rel="imagebox-four" href="assets/images/books/Wisdom/kiore_big.jpg"><img src="assets/images/books/Wisdom/Thumbs/wisdom_kiore_small.jpg" alt="wfw_kiore" width="62" height="107" /></a></li>
<li class="new-flight"><a title="Cappelen forlag: New Flight" rel="imagebox-new" href="assets/images/books/New_Flight/newflight_alv_big.jpg"><img src="assets/images/books/New_Flight/Thumnails/newflight_alv_small.jpg" alt="nf_alv" width="77" height="105" /></a></li>
<li class="new-flight"><a title="Cappelen forlag: New Flight" rel="imagebox-new" href="assets/images/books/New_Flight/newflight_aboriginal_big.jpg"><img src="assets/images/books/New_Flight/Thumnails/newflight_aboriginal_small.jpg" alt="nf_aboriginee" width="77" height="105" /></a></li>
<li class="new-flight"><a title="Cappelen forlag: New Flight" rel="imagebox-new" href="assets/images/books/New_Flight/newflight_monkrocket_big.jpg"><img src="assets/images/books/New_Flight/Thumnails/newflight_monkrocket_small.jpg" alt="nf_munkerakett" width="77" height="105" /></a></li>
<li class="teen-angels"><a title="Findhorn Press: Teen-Angels" rel="imagebox-teen" href="assets/images/books/Teenangels/teen_comfort_big.jpg"><img src="assets/images/books/Teenangels/Thumbs/teen_comfort_small.jpg" alt="ta_comfort" width="77" height="105" /></a></li>
<li class="cumulus"><a title="Aschehoug forlag: Cumulus" rel="imagebox-cumulus" href="assets/images/books/Cumulus/cumulus_heks_big.jpg"><img src="assets/images/books/Cumulus/Thumbnails/cumulus_heks_small.jpg" alt="cumulus_heks" width="77" height="105" /></a></li>
<li class="messages-from-the-wee-folk"><a title="Windpferd Verlag, AGMuller: Messages from the Wee Folk" rel="imagebox-wee" href="assets/images/books/Wee_Folk/weefolk_peace_big.jpg"><img src="assets/images/books/Wee_Folk/Thumbs/weefolk_peace_small.jpg" alt="wf_peace" width="77" height="105" /></a></li>
<li class="wisdom-of-four-winds"><a title="TStonePrint Press, Kamsha Verlag: Wisdom of the Four Winds" rel="imagebox-four" href="assets/images/books/Wisdom/wisdom_rata_big.jpg"><img src="assets/images/books/Wisdom/Thumbs/wisdom_rata_small.jpg" alt="wfw_rata" width="62" height="106" /></a></li>
<li class="new-flight"><a title="Cappelen forlag: New Flight" rel="imagebox-new" href="assets/images/books/New_Flight/newflight_cat&amp;monkey_big.jpg"><img src="assets/images/books/New_Flight/Thumnails/newflight_cat&amp;monkey_small.jpg" alt="nf_katt_apekatt" width="77" height="105" /></a></li>
<li class="new-flight"><a title="Cappelen forlag: New Flight" rel="imagebox-new" href="assets/images/books/New_Flight/newflight_frukt_big.jpg"><img src="assets/images/books/New_Flight/Thumnails/newflight_frukt_small.jpg" alt="nf_frukt" width="77" height="105" /></a></li>
<li class="new-flight"><a title="Cappelen forlag: New Flight" rel="imagebox-new" href="assets/images/books/New_Flight/newflight_newspaperdress_big.jpg"><img src="assets/images/books/New_Flight/Thumnails/newflight_newspaperdress_small.jpg" alt="nf_aviskjole" width="77" height="105" /></a></li>
<li class="teen-angels"><a title="Findhorn Press: Teen-Angels" rel="imagebox-teen" href="assets/images/books/Teenangels/teen_gratitude_big.jpg"><img src="assets/images/books/Teenangels/Thumbs/teen_gratitude_small.jpg" alt="ta_gratitude" width="77" height="105" /></a></li>
<li class="cumulus"><a title="Aschehoug forlag: Cumulus" rel="imagebox-cumulus" href="assets/images/books/Cumulus/cumulus_pizza_big.jpg"><img src="assets/images/books/Cumulus/Thumbnails/cumulus_pizza_small.jpg" alt="cumulus_pizza" width="77" height="105" /></a></li>
<li class="messages-from-the-wee-folk"><a title="Windpferd Verlag, AGMuller: Messages from the Wee Folk" rel="imagebox-wee" href="assets/images/books/Wee_Folk/weefolk_power_big.jpg"><img src="assets/images/books/Wee_Folk/Thumbs/weefolk_power_small.jpg" alt="wf_power" width="73" height="105" /></a></li>
<li class="wisdom-of-four-winds"><a title="StonePrint Press, Kamsha Verlag: Wisdom of the Four Winds" rel="imagebox-four" href="assets/images/books/Wisdom/hawk_big.jpg"><img src="assets/images/books/Wisdom/Thumbs/wisdom_hawk_small.jpg" alt="wfw_hawk" width="62" height="107" /></a></li>
<li class="new-flight"><a title="Cappelen forlag: New Flight" rel="imagebox-new" href="assets/images/books/New_Flight/newflight_alver_big.jpg"><img src="assets/images/books/New_Flight/Thumnails/newflight_alver_small.jpg" alt="nf_alver" width="77" height="105" /></a></li>
<li class="new-flight"><a title="Cappelen forlag: New Flight" rel="imagebox-new" href="assets/images/books/New_Flight/newflight_fly_big.jpg"><img src="assets/images/books/New_Flight/Thumnails/newflight_fly_small.jpg" alt="nf_flue" width="77" height="105" /></a></li>
<li class="new-flight"><a title="Cappelen forlag: New Flight" rel="imagebox-new" href="assets/images/books/New_Flight/newflight_pig_big.jpg"><img src="assets/images/books/New_Flight/Thumnails/newflight_pig_small.jpg" alt="nf_gris" width="77" height="105" /></a></li>
<li class="teen-angels"><a title="Findhorn Press: Teen-Angels" rel="imagebox-teen" href="assets/images/books/Teenangels/teen_laughter_big.jpg"><img src="assets/images/books/Teenangels/Thumbs/teen_laughter_small.jpg" alt="ta_laughter" width="77" height="105" /></a></li>
<li class="cumulus"><a title="Aschehoug forlag: Cumulus" rel="imagebox-cumulus" href="assets/images/books/Cumulus/cumulus_snolek_big.jpg"><img src="assets/images/books/Cumulus/Thumbnails/cumulus_snolek_small.jpg" alt="cumulus_snolek" width="77" height="105" /></a></li>
<li class="messages-from-the-wee-folk"><a title="Windpferd Verlag, AGMuller: Messages from the Wee Folk" rel="imagebox-wee" href="assets/images/books/Wee_Folk/weefolk_release_big.jpg"><img src="assets/images/books/Wee_Folk/Thumbs/weefolk_release_small.jpg" alt="wf_release" width="73" height="105" /></a></li>
<li class="wisdom-of-four-winds"><a title="StonePrint Press, Kamsha Verlag: Wisdom of the Four Winds" rel="imagebox-four" href="assets/images/books/Wisdom/wisdom_stone_big.jpg"><img src="assets/images/books/Wisdom/Thumbs/wisdom_stone_small.jpg" alt="wfw_sgreenstone" width="62" height="105" /></a></li>
<li class="andre"><a title="StonePrint Press, Kamsha Verlag: Dolphin" rel="imagebox-andre" href="assets/images/Andre_illustrasjoner/dolphin_big.jpg"><img src="assets/images/Andre_illustrasjoner/Thums/dolphin_small.jpg" alt="Dolphin" width="77" height="105" /></a></li>
<li class="wisdom-of-four-winds"><a title="StonePrint Press, Kamsha Verlag: Wisdom of the Four Winds" rel="imagebox-four" href="assets/images/books/Wisdom/woodpigeon_big.jpg"><img src="assets/images/books/Wisdom/Thumbs/wisdom_woodpigeon_small.jpg" alt="wfw_woodpigeon" width="62" height="105" /></a></li>
<li class="wisdom-of-four-winds"><a title="StonePrint Press, Kamsha Verlag: Wisdom of the Four Winds" rel="imagebox-four" href="assets/images/books/Wisdom/wisdom_seahorse_big.jpg"><img src="assets/images/books/Wisdom/Thumbs/wisdom_seahorse_small.jpg" alt="wfw_seahorse" width="63" height="106" /></a></li>
<li class="teen-angels"><a title="Findhorn Press: Teen-Angels" rel="imagebox-teen" href="assets/images/books/Teenangels/teen_positivity_big.jpg"><img src="assets/images/books/Teenangels/Thumbs/teen_positivity_small.jpg" alt="ta_positivity" width="77" height="105" /></a></li>
<li class="teen-angels"><a title="Findhorn Press: Teen-Angels" rel="imagebox-teen" href="assets/images/books/Teenangels/teen_winning_big.jpg"><img src="assets/images/books/Teenangels/Thumbs/teen_winning_small.jpg" alt="ta_winning" width="77" height="105" /></a></li>
<li class="wisdom-of-four-winds"><a title="StonePrint Press, Kamsha Verlag: Wisdom of the Four Winds" rel="imagebox-four" href="assets/images/books/Wisdom/wisdom_kiwi_big.jpg"><img src="assets/images/books/Wisdom/Thumbs/wisdom_kiwi_small.jpg" alt="wfw_kiwi" width="62" height="105" /></a></li>
<li class="wisdom-of-four-winds"><a title="StonePrint Press, Kamsha Verlag: Wisdom of the Four Winds" rel="imagebox-four" href="assets/images/books/Wisdom/wisdom_spider_big.jpg"><img src="assets/images/books/Wisdom/Thumbs/wisdom_spider_small.jpg" alt="wfw_spider" width="62" height="108" /></a></li>
</ul>
</div>
</div>
<!-- End of webtable --></div>
<p><!-- End of gallerimain--></p>